---
output:
  html_document: default
  word_document: default
  pdf_document: default
---


# Gestion des Loyers - Gen2

Document créé le 3/12/2021

Mis à jour le `r format(Sys.time(), '%a-%d/%m/%Y')`



```{r setup, include=FALSE, eval=FALSE,results='hide',message=FALSE,warning=FALSE}
Fichier: `r get(env = parent.frame(n = 8), 'input')`  
CWD: `r getwd()`

knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html")

```
```{r Get Librairies, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
rm(list = ls())          # Supprime tous les objets
graphics.off()           # Ferme toutes les fenêtres de graphique
#cat("\014")              # Nettoie la console (équivalent de Ctrl+L)
g <- getwd()
LibDir <- "./ModulesR"

source(file.path(LibDir , "GetLoyer.R"))
source(file.path(LibDir , "GetIndex.R"))
source(file.path(LibDir , "MakeLotLoc.R"))
source(file.path(LibDir , "Merge2LotLoc.R"))
source(file.path(LibDir , "PlotLoyer.R"))
source(file.path(LibDir , "Suivi_LoyersLibrariesv2025_09.R"))
library(zoo)
#install.packages("gt")
library(gt)

```

```{r GetExternal Data, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}

IndexDF <- GetIndex() 
IndexDF <- IndexDF %>% select("Date","Index","Mois","An")
AllLoyers <- GetLoyer("./Input/SuiviLoyers.xlsx")
# à ce stade AllLoyer Contient toutes les données de base pour calculer le noubeau loyer dont Date4CalculNouveauLoyer, Mois ... et Date ...

# print(AllLoyers)
# on va verifier les index de Suivi_Loyer
Check_Index <- left_join(AllLoyers,IndexDF, by=c("DateIndex"="Date")) %>% filter(Index.x != Index.y)
ifelse(nrow(Check_Index>0), {print("Erreur in Suivi_Loyer.xlsx")},{print("Indexes in Suivi_Loyer are OK")})
```

```{r On va générer toutes les dates  mensuelles utiles et les index relatifs, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
# On va générer toutes les dates  mensuelles nécessaires
StartDate <- min(AllLoyers$DateIndex)
today <- Sys.Date() # or Sys.time() for POSIXct
EndDate <- floor_date(today, unit = "month")
AllDates <- IndexDF %>% filter(Date >= StartDate) %>% select(Date,Index)
AllDates$Mois <- month(ymd(AllDates$Date))
AllDates$An <-year(ymd(AllDates$Date))
# ce stade, AllDates Contient les indexes depuis le début des locations
```

```{r Fonction Indexation, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
jcbIndexation <- function( CurrentLoc,CurrentLot){
  CurrentLotLoc <- paste(CurrentLot,CurrentLoc,sep='_')
  # on va chercher le range de dates pour la combinasion Lot-Loc 
  FirstDate4CurrentLotLoc <- AllLoyers$DateDébut[AllLoyers$LotLoc == CurrentLotLoc]
  LastDate <- Sys.Date()
  # On va créer pour chaque locataire un texte qui reprend toutes les données utiles pour faire la lettre ...
  # on va chercher les index pour ce range de Dates 
  NeededIndexes <- AllDates  %>% filter(Date >= FirstDate4CurrentLotLoc & Date <= LastDate) %>% mutate ( LotLoc = CurrentLotLoc)
  # on merge NeededIndexes avec AllLoyers pour LotLoc
  # On va faire un df par LoLoc
  CurrentDF <- left_join(NeededIndexes, AllLoyers, by = "LotLoc")
  #
  # Texte de Lettre
  #
  Texte1 <- paste("Pour le lot",CurrentLot,", un bail a été signé le",CurrentDF$DateSignBail[1],"avec le Locataire",CurrentLoc)
  Texte2 <- paste("Le loyer convenu est de",CurrentDF$Loyer[1],"Euros, à l' index",CurrentDF$Index.y[1])
  Texte3 <- paste("La date d' entrée en vigueur du bail est le ",CurrentDF$DateDébut[1])
  Texte4 <- paste("La date pour le calcul du nouvel index est le 01-",CurrentDF$Mois4CalculNouveauLoyer[1])
  Texte5 <- "ci-dessous les loyers applicables, pour tous les mois depuis le début"
  TEXTE <- paste (Texte1,Texte2,Texte3,Texte4,Texte5,sep="<br>")
  Indexation <- CurrentDF %>% select(Date,LotLoc,Loyer,Index.y,Index.x)
  Indexation <- Indexation %>% mutate(LoyerIndexé = Loyer*Index.x/Index.y)
  Indexation$MoisAnniv <-ifelse(CurrentDF$Mois4CalculNouveauLoyer[1] == CurrentDF$Mois,TRUE,FALSE)
  #print(Indexation)
  Table <- Indexation |>
    gt() |>
    tab_header(title = html(TEXTE)) |>
    tab_style(style = cell_text(weight = "bold"),locations = cells_body(rows = MoisAnniv == TRUE))
    
return (Table)
  
}
```



```{r Generate_Result_par_Lot, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
ListOfLots <- as.data.frame(table(AllLoyers$Lot))
jcbEssers <- jcbIndexation("Essers","App21")
(jcbEssers)

